/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as PawnRouteImport } from './routes/pawn'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as QuoteReceivedRouteImport } from './routes/quote_.received'
import { Route as VisitSlugRouteImport } from './routes/visit_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const PawnRoute = PawnRouteImport.update({
  id: '/pawn',
  path: '/pawn',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteReceivedRoute = QuoteReceivedRouteImport.update({
  id: '/quote_/received',
  path: '/quote/received',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitSlugRoute = VisitSlugRouteImport.update({
  id: '/visit_/$slug',
  path: '/visit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gold': typeof GoldRoute
  '/pawn': typeof PawnRoute
  '/quote': typeof QuoteRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/quote/received': typeof QuoteReceivedRoute
  '/visit/$slug': typeof VisitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gold': typeof GoldRoute
  '/pawn': typeof PawnRoute
  '/quote': typeof QuoteRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/quote/received': typeof QuoteReceivedRoute
  '/visit/$slug': typeof VisitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gold': typeof GoldRoute
  '/pawn': typeof PawnRoute
  '/quote': typeof QuoteRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/quote_/received': typeof QuoteReceivedRoute
  '/visit_/$slug': typeof VisitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gold'
    | '/pawn'
    | '/quote'
    | '/sell'
    | '/shop'
    | '/visit'
    | '/quote/received'
    | '/visit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gold'
    | '/pawn'
    | '/quote'
    | '/sell'
    | '/shop'
    | '/visit'
    | '/quote/received'
    | '/visit/$slug'
  id:
    | '__root__'
    | '/'
    | '/gold'
    | '/pawn'
    | '/quote'
    | '/sell'
    | '/shop'
    | '/visit'
    | '/quote_/received'
    | '/visit_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoldRoute: typeof GoldRoute
  PawnRoute: typeof PawnRoute
  QuoteRoute: typeof QuoteRoute
  SellRoute: typeof SellRoute
  ShopRoute: typeof ShopRoute
  VisitRoute: typeof VisitRoute
  QuoteReceivedRoute: typeof QuoteReceivedRoute
  VisitSlugRoute: typeof VisitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pawn': {
      id: '/pawn'
      path: '/pawn'
      fullPath: '/pawn'
      preLoaderRoute: typeof PawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote_/received': {
      id: '/quote_/received'
      path: '/quote/received'
      fullPath: '/quote/received'
      preLoaderRoute: typeof QuoteReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit_/$slug': {
      id: '/visit_/$slug'
      path: '/visit/$slug'
      fullPath: '/visit/$slug'
      preLoaderRoute: typeof VisitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoldRoute: GoldRoute,
  PawnRoute: PawnRoute,
  QuoteRoute: QuoteRoute,
  SellRoute: SellRoute,
  ShopRoute: ShopRoute,
  VisitRoute: VisitRoute,
  QuoteReceivedRoute: QuoteReceivedRoute,
  VisitSlugRoute: VisitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
